import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

async function main() {
  await prisma.product.deleteMany()

  await prisma.product.createMany({
    data: [
      {
        name: "Apple MacBook Pro 14-inch M3",
        description: "لابتوب احترافي بشريحة M3 مع شاشة Liquid Retina XDR وبطارية تدوم 18 ساعة.",
        price: 1999.99,
        images: ["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600"],
        category: "Electronics",
        brand: "Apple",
        model: "MacBook Pro 14 M3",
        stock: 15,
        featured: true,
        rating: 4.9,
      },
      {
        name: "Samsung Galaxy S24 Ultra",
        description: "هاتف ذكي متطور مع كاميرا 200MP وقلم S Pen مدمج وشاشة Dynamic AMOLED 2X.",
        price: 1299.99,
        images: ["https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600"],
        category: "Electronics",
        brand: "Samsung",
        model: "Galaxy S24 Ultra",
        stock: 30,
        featured: true,
        rating: 4.8,
      },
      {
        name: "Sony WH-1000XM5",
        description: "سماعات لاسلكية بأفضل تقنية إلغاء ضوضاء في السوق مع صوت Hi-Res Audio.",
        price: 349.99,
        images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600"],
        category: "Electronics",
        brand: "Sony",
        model: "WH-1000XM5",
        stock: 50,
        featured: false,
        rating: 4.7,
      },
      {
        name: "Nike Air Max 270",
        description: "حذاء رياضي مريح مع وسادة هوائية Max Air لأقصى راحة طوال اليوم.",
        price: 149.99,
        images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600"],
        category: "Fashion",
        brand: "Nike",
        model: "Air Max 270",
        stock: 100,
        featured: true,
        rating: 4.6,
      },
      {
        name: "Dyson V15 Detect",
        description: "مكنسة كهربائية لاسلكية بليزر يكشف الغبار الخفي وقوة شفط استثنائية.",
        price: 699.99,
        images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600"],
        category: "Home",
        brand: "Dyson",
        model: "V15 Detect",
        stock: 20,
        featured: false,
        rating: 4.8,
      },
      {
        name: "iPad Pro 12.9-inch M2",
        description: "تابلت احترافي بشريحة M2 وشاشة Liquid Retina XDR مع دعم Apple Pencil Pro.",
        price: 1099.99,
        images: ["https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600"],
        category: "Electronics",
        brand: "Apple",
        model: "iPad Pro 12.9 M2",
        stock: 25,
        featured: true,
        rating: 4.9,
      },
      {
        name: "Adidas Ultraboost 23",
        description: "حذاء جري بتقنية Boost للحصول على أقصى طاقة إرجاع مع كل خطوة.",
        price: 189.99,
        images: ["https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600"],
        category: "Fashion",
        brand: "Adidas",
        model: "Ultraboost 23",
        stock: 80,
        featured: false,
        rating: 4.5,
      },
      {
        name: "Nespresso Vertuo Next",
        description: "ماكينة قهوة ذكية تتعرف تلقائياً على كل كبسولة وتضبط درجة الحرارة والحجم.",
        price: 179.99,
        images: ["https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600"],
        category: "Home",
        brand: "Nespresso",
        model: "Vertuo Next",
        stock: 40,
        featured: false,
        rating: 4.4,
      },
      {
        name: "Canon EOS R6 Mark II",
        description: "كاميرا mirrorless احترافية بسرعة 40fps وتثبيت صورة متطور لتصوير مثالي.",
        price: 2499.99,
        images: ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600"],
        category: "Electronics",
        brand: "Canon",
        model: "EOS R6 Mark II",
        stock: 10,
        featured: true,
        rating: 4.9,
      },
      {
        name: "IKEA POÄNG Armchair",
        description: "كرسي بذراعين كلاسيكي بإطار بيرش وحشوة مريحة، تصميم اسكندنافي خالد.",
        price: 129.99,
        images: ["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600"],
        category: "Home",
        brand: "IKEA",
        model: "POÄNG",
        stock: 60,
        featured: false,
        rating: 4.3,
      },
      {
        name: "PlayStation 5 Console",
        description: "أحدث جيل من PlayStation بمعالج قوي وSSD فائق السرعة لتجربة ألعاب لا تُنسى.",
        price: 499.99,
        images: ["https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=600"],
        category: "Electronics",
        brand: "Sony",
        model: "PS5",
        stock: 8,
        featured: true,
        rating: 4.8,
      },
      {
        name: "Levi's 501 Original Jeans",
        description: "جينز كلاسيكي بقصة مستقيمة، الأيقونة الأزلية في عالم الموضة منذ 1873.",
        price: 69.99,
        images: ["https://images.unsplash.com/photo-1542272604-787c3835535d?w=600"],
        category: "Fashion",
        brand: "Levi's",
        model: "501 Original",
        stock: 200,
        featured: false,
        rating: 4.6,
      },
    ],
  })

  console.log("✅ تم إضافة 12 منتج بنجاح!")
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
